// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayaAutos.API.Data;

#nullable disable

namespace PlayaAutos.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511151541_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlayaAutos.API.Models.Cita", b =>
                {
                    b.Property<int>("CitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CitaId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoCitaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCita")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("int");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.HasKey("CitaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EstadoCitaId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CI_RUC")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RangoPrecioMax")
                        .HasColumnType("numeric(15,0)");

                    b.Property<decimal?>("RangoPrecioMin")
                        .HasColumnType("numeric(15,0)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ClienteId");

                    b.HasIndex("CI_RUC")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasFilter("[UsuarioId] IS NOT NULL");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.CondicionVehiculo", b =>
                {
                    b.Property<int>("CondicionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CondicionId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CondicionId");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("CondicionesVehiculo");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Consignante", b =>
                {
                    b.Property<int>("ConsignanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsignanteId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PorcentajeComisionDefault")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ConsignanteId");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("Consignantes");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.ContratoConsigna", b =>
                {
                    b.Property<int>("ContratoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContratoId"));

                    b.Property<string>("Clausulas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConsignanteId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroContrato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PorcentajeComision")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RutaPDF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("ContratoId");

                    b.HasIndex("ConsignanteId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("ContratosConsigna");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Cuota", b =>
                {
                    b.Property<int>("CuotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CuotaId"));

                    b.Property<string>("ComprobanteImagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRegistroPago")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FormaPagoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric(15,0)");

                    b.Property<decimal?>("MontoPagado")
                        .HasColumnType("numeric(15,0)");

                    b.Property<decimal?>("MontoRecargo")
                        .HasColumnType("numeric(15,0)");

                    b.Property<int>("NumeroCuota")
                        .HasColumnType("int");

                    b.Property<string>("ObservacionPago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("CuotaId");

                    b.HasIndex("FormaPagoId");

                    b.HasIndex("VentaId");

                    b.ToTable("Cuotas");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.EstadoCita", b =>
                {
                    b.Property<int>("EstadoCitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoCitaId"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstadoCitaId");

                    b.ToTable("EstadosCita");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.EstadoVehiculo", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("PermiteVenta")
                        .HasColumnType("bit");

                    b.Property<bool>("VisibleEnCatalogo")
                        .HasColumnType("bit");

                    b.HasKey("EstadoId");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("EstadosVehiculo");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Factura", b =>
                {
                    b.Property<int>("FacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacturaId"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IVA")
                        .HasColumnType("numeric(15,0)");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RutaPDF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(15,0)");

                    b.Property<int>("TimbradoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(15,0)");

                    b.Property<int>("UsuarioGeneracion")
                        .HasColumnType("int");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("FacturaId");

                    b.HasIndex("NumeroFactura")
                        .IsUnique();

                    b.HasIndex("TimbradoId");

                    b.HasIndex("VentaId")
                        .IsUnique();

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.FormaPago", b =>
                {
                    b.Property<int>("FormaPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormaPagoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GeneraNotaCredito")
                        .HasColumnType("bit");

                    b.HasKey("FormaPagoId");

                    b.ToTable("FormasPago");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.FotoVehiculo", b =>
                {
                    b.Property<int>("FotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FotoId"));

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("FotoId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("FotosVehiculo");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.GastoVehiculo", b =>
                {
                    b.Property<int>("GastoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GastoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric(15,0)");

                    b.Property<string>("Proveedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoGastoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioRegistro")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("GastoId");

                    b.HasIndex("TipoGastoId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("GastosVehiculo");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Marca", b =>
                {
                    b.Property<int>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarcaId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MarcaId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Modelo", b =>
                {
                    b.Property<int>("ModeloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModeloId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModeloId");

                    b.HasIndex("MarcaId");

                    b.ToTable("Modelos");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.MovimientoCaja", b =>
                {
                    b.Property<int>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovimientoId"));

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CuotaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FormaPagoId")
                        .HasColumnType("int");

                    b.Property<int?>("GastoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric(15,0)");

                    b.Property<int>("TipoMovimientoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioRegistro")
                        .HasColumnType("int");

                    b.Property<int?>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("MovimientoId");

                    b.HasIndex("CuotaId")
                        .IsUnique()
                        .HasFilter("[CuotaId] IS NOT NULL");

                    b.HasIndex("GastoId")
                        .IsUnique()
                        .HasFilter("[GastoId] IS NOT NULL");

                    b.HasIndex("TipoMovimientoId");

                    b.HasIndex("VentaId");

                    b.ToTable("MovimientosCaja");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.NotaCredito", b =>
                {
                    b.Property<int>("NotaCreditoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotaCreditoId"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric(15,0)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroNota")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RutaPDF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TasacionVehiculoId")
                        .HasColumnType("int");

                    b.Property<int>("TimbradoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioGeneracion")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("NotaCreditoId");

                    b.HasIndex("NumeroNota")
                        .IsUnique();

                    b.HasIndex("TasacionVehiculoId");

                    b.HasIndex("TimbradoId");

                    b.HasIndex("VehiculoId");

                    b.HasIndex("VentaId")
                        .IsUnique();

                    b.ToTable("NotasCredito");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.OrigenVehiculo", b =>
                {
                    b.Property<int>("OrigenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrigenId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrigenId");

                    b.ToTable("OrigenesVehiculo");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.PagoVenta", b =>
                {
                    b.Property<int>("PagoVentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoVentaId"));

                    b.Property<string>("ComprobanteImagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormaPagoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric(15,0)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TasacionVehiculoId")
                        .HasColumnType("int");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("PagoVentaId");

                    b.HasIndex("FormaPagoId");

                    b.HasIndex("TasacionVehiculoId");

                    b.HasIndex("VentaId");

                    b.ToTable("PagosVenta");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.TasacionVehiculo", b =>
                {
                    b.Property<int>("TasacionVehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TasacionVehiculoId"));

                    b.Property<int>("AnhoVehiculo")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("ColorVehiculo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoGeneralVehiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoTasacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaTasacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("KilometrajeVehiculo")
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("MarcaVehiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModeloVehiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("numeric(15,0)");

                    b.Property<int>("UsuarioTasacion")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTasacion")
                        .HasColumnType("numeric(15,0)");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("TasacionVehiculoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("TasacionesVehiculo");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Timbrado", b =>
                {
                    b.Property<int>("TimbradoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimbradoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<long>("NumeroDesde")
                        .HasColumnType("bigint");

                    b.Property<long>("NumeroHasta")
                        .HasColumnType("bigint");

                    b.Property<string>("NumeroTimbrado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UltimoNumeroUsado")
                        .HasColumnType("bigint");

                    b.HasKey("TimbradoId");

                    b.ToTable("Timbrados");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.TipoGasto", b =>
                {
                    b.Property<int>("TipoGastoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoGastoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TipoGastoId");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("TiposGasto");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.TipoMovimiento", b =>
                {
                    b.Property<int>("TipoMovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoMovimientoId"));

                    b.Property<bool>("AfectaCaja")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoMovimientoId");

                    b.ToTable("TiposMovimiento");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.TipoVehiculo", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TipoId");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("TiposVehiculo");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.TipoVenta", b =>
                {
                    b.Property<int>("TipoVentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoVentaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiereFinanciacion")
                        .HasColumnType("bit");

                    b.HasKey("TipoVentaId");

                    b.ToTable("TiposVenta");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("ActivoUsuario")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAltaUsuario")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioPhone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("UsuarioEmail")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehiculoId"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CondicionId")
                        .HasColumnType("int");

                    b.Property<int?>("ConsignanteId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostoAdquisicion")
                        .HasColumnType("numeric(15,0)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaConsigna")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Kilometraje")
                        .HasColumnType("numeric(10,0)");

                    b.Property<int>("ModeloId")
                        .HasColumnType("int");

                    b.Property<int>("OrigenId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PorcentajeComision")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("numeric(15,0)");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioAlta")
                        .HasColumnType("int");

                    b.HasKey("VehiculoId");

                    b.HasIndex("CodigoInterno")
                        .IsUnique();

                    b.HasIndex("CondicionId");

                    b.HasIndex("ConsignanteId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("ModeloId");

                    b.HasIndex("OrigenId");

                    b.HasIndex("TipoId");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Venta", b =>
                {
                    b.Property<int>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VentaId"));

                    b.Property<int?>("CantidadCuotas")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MontoEntrada")
                        .HasColumnType("numeric(15,0)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric(15,0)");

                    b.Property<string>("MotivoAnulacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SaldoFinanciado")
                        .HasColumnType("numeric(15,0)");

                    b.Property<decimal?>("TasaInteres")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TipoVentaId")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.HasKey("VentaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TipoVentaId");

                    b.HasIndex("VehiculoId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Cita", b =>
                {
                    b.HasOne("PlayaAutos.API.Models.Cliente", "Cliente")
                        .WithMany("Citas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlayaAutos.API.Models.EstadoCita", "EstadoCita")
                        .WithMany("Citas")
                        .HasForeignKey("EstadoCitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayaAutos.API.Models.Vehiculo", "Vehiculo")
                        .WithMany("Citas")
                        .HasForeignKey("VehiculoId");

                    b.Navigation("Cliente");

                    b.Navigation("EstadoCita");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Cliente", b =>
                {
                    b.HasOne("PlayaAutos.API.Models.Usuario", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("PlayaAutos.API.Models.Cliente", "UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Consignante", b =>
                {
                    b.HasOne("PlayaAutos.API.Models.Cliente", "Cliente")
                        .WithOne("Consignante")
                        .HasForeignKey("PlayaAutos.API.Models.Consignante", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.ContratoConsigna", b =>
                {
                    b.HasOne("PlayaAutos.API.Models.Consignante", "Consignante")
                        .WithMany("ContratosConsigna")
                        .HasForeignKey("ConsignanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayaAutos.API.Models.Vehiculo", "Vehiculo")
                        .WithMany("ContratosConsigna")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consignante");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Cuota", b =>
                {
                    b.HasOne("PlayaAutos.API.Models.FormaPago", "FormaPago")
                        .WithMany("Cuotas")
                        .HasForeignKey("FormaPagoId");

                    b.HasOne("PlayaAutos.API.Models.Venta", "Venta")
                        .WithMany("Cuotas")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaPago");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Factura", b =>
                {
                    b.HasOne("PlayaAutos.API.Models.Timbrado", "Timbrado")
                        .WithMany("Facturas")
                        .HasForeignKey("TimbradoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayaAutos.API.Models.Venta", "Venta")
                        .WithOne("Factura")
                        .HasForeignKey("PlayaAutos.API.Models.Factura", "VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Timbrado");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.FotoVehiculo", b =>
                {
                    b.HasOne("PlayaAutos.API.Models.Vehiculo", "Vehiculo")
                        .WithMany("Fotos")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.GastoVehiculo", b =>
                {
                    b.HasOne("PlayaAutos.API.Models.TipoGasto", "TipoGasto")
                        .WithMany("GastosVehiculo")
                        .HasForeignKey("TipoGastoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayaAutos.API.Models.Vehiculo", "Vehiculo")
                        .WithMany("Gastos")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoGasto");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Modelo", b =>
                {
                    b.HasOne("PlayaAutos.API.Models.Marca", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.MovimientoCaja", b =>
                {
                    b.HasOne("PlayaAutos.API.Models.Cuota", "Cuota")
                        .WithOne("MovimientoCaja")
                        .HasForeignKey("PlayaAutos.API.Models.MovimientoCaja", "CuotaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlayaAutos.API.Models.GastoVehiculo", "GastoVehiculo")
                        .WithOne("MovimientoCaja")
                        .HasForeignKey("PlayaAutos.API.Models.MovimientoCaja", "GastoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlayaAutos.API.Models.TipoMovimiento", "TipoMovimiento")
                        .WithMany("MovimientosCaja")
                        .HasForeignKey("TipoMovimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayaAutos.API.Models.Venta", "Venta")
                        .WithMany("MovimientosCaja")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cuota");

                    b.Navigation("GastoVehiculo");

                    b.Navigation("TipoMovimiento");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.NotaCredito", b =>
                {
                    b.HasOne("PlayaAutos.API.Models.TasacionVehiculo", "TasacionVehiculo")
                        .WithMany()
                        .HasForeignKey("TasacionVehiculoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlayaAutos.API.Models.Timbrado", "Timbrado")
                        .WithMany("NotasCredito")
                        .HasForeignKey("TimbradoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayaAutos.API.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayaAutos.API.Models.Venta", "Venta")
                        .WithOne("NotaCredito")
                        .HasForeignKey("PlayaAutos.API.Models.NotaCredito", "VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TasacionVehiculo");

                    b.Navigation("Timbrado");

                    b.Navigation("Vehiculo");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.PagoVenta", b =>
                {
                    b.HasOne("PlayaAutos.API.Models.FormaPago", "FormaPago")
                        .WithMany("PagosVenta")
                        .HasForeignKey("FormaPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlayaAutos.API.Models.TasacionVehiculo", "TasacionVehiculo")
                        .WithMany("PagosVenta")
                        .HasForeignKey("TasacionVehiculoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlayaAutos.API.Models.Venta", "Venta")
                        .WithMany("PagosVenta")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FormaPago");

                    b.Navigation("TasacionVehiculo");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.TasacionVehiculo", b =>
                {
                    b.HasOne("PlayaAutos.API.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlayaAutos.API.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Vehiculo", b =>
                {
                    b.HasOne("PlayaAutos.API.Models.CondicionVehiculo", "Condicion")
                        .WithMany("Vehiculos")
                        .HasForeignKey("CondicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayaAutos.API.Models.Consignante", "Consignante")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ConsignanteId");

                    b.HasOne("PlayaAutos.API.Models.EstadoVehiculo", "Estado")
                        .WithMany("Vehiculos")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayaAutos.API.Models.Modelo", "Modelo")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayaAutos.API.Models.OrigenVehiculo", "Origen")
                        .WithMany("Vehiculos")
                        .HasForeignKey("OrigenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayaAutos.API.Models.TipoVehiculo", "Tipo")
                        .WithMany("Vehiculos")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condicion");

                    b.Navigation("Consignante");

                    b.Navigation("Estado");

                    b.Navigation("Modelo");

                    b.Navigation("Origen");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Venta", b =>
                {
                    b.HasOne("PlayaAutos.API.Models.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlayaAutos.API.Models.TipoVenta", "TipoVenta")
                        .WithMany("Ventas")
                        .HasForeignKey("TipoVentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayaAutos.API.Models.Vehiculo", "Vehiculo")
                        .WithMany("Ventas")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlayaAutos.API.Models.Usuario", "Vendedor")
                        .WithMany("Ventas")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("TipoVenta");

                    b.Navigation("Vehiculo");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Cliente", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Consignante");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.CondicionVehiculo", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Consignante", b =>
                {
                    b.Navigation("ContratosConsigna");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Cuota", b =>
                {
                    b.Navigation("MovimientoCaja");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.EstadoCita", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.EstadoVehiculo", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.FormaPago", b =>
                {
                    b.Navigation("Cuotas");

                    b.Navigation("PagosVenta");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.GastoVehiculo", b =>
                {
                    b.Navigation("MovimientoCaja");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Marca", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Modelo", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.OrigenVehiculo", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.TasacionVehiculo", b =>
                {
                    b.Navigation("PagosVenta");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Timbrado", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("NotasCredito");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.TipoGasto", b =>
                {
                    b.Navigation("GastosVehiculo");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.TipoMovimiento", b =>
                {
                    b.Navigation("MovimientosCaja");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.TipoVehiculo", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.TipoVenta", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Usuario", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Vehiculo", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("ContratosConsigna");

                    b.Navigation("Fotos");

                    b.Navigation("Gastos");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("PlayaAutos.API.Models.Venta", b =>
                {
                    b.Navigation("Cuotas");

                    b.Navigation("Factura");

                    b.Navigation("MovimientosCaja");

                    b.Navigation("NotaCredito");

                    b.Navigation("PagosVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
